### ISSUE TITLE
Listing applications return 403 forbidden

### ISSUE THREAD

**Issue by pavinduLakshan** [shashimalcse/asgardeo-cli#15]
$subject

https://github.com/user-attachments/assets/e0ca27ef-3da5-4da3-b671-27b0aa8c1d97

**Comment by pavinduLakshan** [comment]
Steps to reproduce:

1. Sign in to Asgardeo and create M2M application
2. Run `asgardeo login` and provide tenant name, client ID and client secret of the created M2M application.
3. Once successfully authenticated, run `asgardeo apps list` to get the applications list.

**Comment by shashimalcse** [comment]
@pavinduLakshan did you get the latest update? I have updated the http client. will check this

**Comment by pavinduLakshan** [comment]
> @pavinduLakshan did you get the latest update? I have updated the http client. will check this

Yes, tried with the latest, but still reproducing

**Comment by sahandilshan** [comment]
Hi @pavinduLakshan 
Does your m2m app have permission to access the applications? Check whether it has `Application Management API` access as shown below in the API Authorization section 
<img width="946" alt="Screenshot 2024-08-19 at 8 36 53 PM" src="https://github.com/user-attachments/assets/8e10d7f1-199c-4df1-8c12-89d88ad702d4">

**Comment by pavinduLakshan** [comment]
@sahandilshan authorize app mgt API to the application fixed the issue. Thanks 👍 

It'd be better to update the readme with this information. I will send a PR
