### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by pavinduLakshan** [shashimalcse/asgardeo-cli#19]
It'd be better to add a license to the project because having no license specified means no one has the right to use, copy or modify the code.

**Comment by shashimalcse** [comment]
@pavinduLakshan what do you suggest?

**Comment by pavinduLakshan** [comment]
MIT license seems good, IMO.

If you are also +1, I can send a PR :)

**Comment by shashimalcse** [comment]
+1 for MIT
